#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Add global gitignore
ln -sf $HOME/.dotfiles/shell/.gitignore-global $HOME/.gitignore-global
git config --global core.excludesfile $HOME/.gitignore-global

# Symlink the Mackup config
ln -sf $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

pushd $HOME/.dotfiles

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
echo 'move composer to /usr/local/bin/composer'
mv -f composer.phar /usr/local/bin/composer

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install node'
echo '-----------'
brew install node

echo 'Install bat'
echo '-----------'
brew install bat

echo 'Install tldr'
echo '------------'
brew install tldr

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install prettyping'
echo '------------------'
brew install prettyping

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install doctl'
echo '-------------'
brew install doctl

echo 'Install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'Install php'
echo '-----------'
brew install php@7.0
brew install php@7.1
brew install php@7.2

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install ext-imagick'
echo '-------------------'
pecl install imagick

echo 'Install ext-memcached'
echo '---------------------'
pecl install memcached

echo 'Install ext-xdebug'
echo '------------------'
pecl install xdebug

echo 'Install ext-redis'
echo '-----------------'
pecl install redis

echo 'Install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

echo 'Install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

echo 'Install phpunit-watcher'
echo '---------------------'
composer global require spatie/phpunit-watcher

echo 'Install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
$HOME/.composer/vendor/bin/valet install

echo 'Install heroku'
echo '--------------'
brew install heroku/brew/heroku

echo 'Install rabbitmq'
echo '----------------'
brew install rabbitmq rabbitmq-c

echo 'Install redis server'
echo '--------------------'
brew install redis

echo 'Install mariadb'
echo '---------------'
brew install mariadb

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install blackfire (agent and probes)'
echo '------------------------------------'
brew tap blackfireio/homebrew-blackfire
brew install blackfire-agent blackfire-php70 blackfire-php71 blackfire-php72

echo 'Install mackup'
echo '--------------'
brew install mackup
