#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

mkdir -p ~/.config

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink the Mackup config
ln -sf $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

ln -sf $HOME/.dotfiles/macos/.mackup $HOME/.mackup

ln -sf $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile
ln -sf $HOME/.dotfiles/shell/.bashrc $HOME/.bashrc
ln -sf $HOME/.dotfiles/shell/.gitignore-global $HOME/.gitignore-global

pushd $HOME/.dotfiles

echo 'Install composer'
echo '----------------'
EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi
php composer-setup.php
rm composer-setup.php
mv composer.phar /usr/local/bin/composer

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install git'
echo '-----------'
brew install git

echo 'Install bash-completion'
echo '-----------------------'
brew install bash-completion

echo 'Install node'
echo '-----------'
brew install node

echo 'Install ruby'
echo '------------'
brew install ruby

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install doctl'
echo '-------------'
brew install doctl

echo 'Install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'Install php'
echo '-----------'
brew install php@7.4
brew install php@8.0

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install ext-imagick'
echo '-------------------'
pecl install imagick

echo 'Install ext-memcached'
echo '---------------------'
pecl install memcached

echo 'Install ext-xdebug'
echo '------------------'
pecl install xdebug

echo 'Install ext-redis'
echo '-----------------'
pecl install redis

echo 'Install ext-amqp'
echo '-----------------'
pecl install amqp

echo 'Install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

echo 'Install phpunit-watcher'
echo '---------------------'
composer global require spatie/phpunit-watcher

echo 'Install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
$HOME/.composer/vendor/bin/valet install

echo 'Install heroku'
echo '--------------'
brew install heroku/brew/heroku

echo 'Install rabbitmq'
echo '----------------'
brew install rabbitmq rabbitmq-c

echo 'Install redis server'
echo '--------------------'
brew install redis

echo 'Install mariadb'
echo '---------------'
brew install mariadb

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install powerline-status'
echo '------------------------'
pip3 install powerline-status

echo 'Install powerline-gitstatus'
echo '---------------------------'
pip3 install powerline-gitstatus

echo 'Install blackfire (agent and probes)'
echo '------------------------------------'
brew tap blackfireio/homebrew-blackfire
brew install blackfire-agent blackfire-php70 blackfire-php71 blackfire-php72 blackfire-php73 blackfire-php74

echo 'Install Fira Code and Mono for Powerline'
brew install homebrew/cask-fonts/font-fira-code
brew install homebrew/cask-fonts/font-fira-mono-for-powerline

echo 'Install mackup'
echo '--------------'
brew install mackup

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions
