#!/usr/bin/env bash

mysides add simensen file:///Users/simensen
mysides add Code file:///Users/simensen/Code
mysides add Sites file:///Users/simensen/Code/sites
mysides remove Desktop
mysides remove Movies
mysides remove Music
